version: "3"
services:
  pismo-banking-apis:
    # container_name: pismo-banking-apis
    image: pismo-banking-apis
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: pismo-banking
      MYSQL_ROOT_PASSWORD: root
